POST http://100.64.0.1:8084/auth/register
Content-Type: application/json

{
  "username": "toms",
  "password": "v12345"
}
###
GET http://100.64.0.1:8084/health
Content-Type: application/json
###
POST http://100.64.0.1:8084/auth/login
Content-Type: application/json

{
  "username": "toms",
  "password": "v12345"
}
###
GET http://100.64.0.1:8084/auth/me
Authorization: Bearer ce90afcc-66c1-456d95d2-d5e297f83e4c

POST http://100.64.0.1:8084/admin/client
authorization: Bearer cxtD0gyEfZqVv7FmpU
Content-Type: application/json

{
  "client_id":"1",
  "client_type":"public",
  "redirect_uris":"http://100.64.0.1:8082/auth",
  "allowed_scopes":"w+"
}
###
GET http://100.64.0.1:8084/oauth/authorize
Content-Type: application/json

{
  "client_id":"2",
  "redirect_uri":"http://100.64.0.1:8082/auth",
  "scope":"w+",
  "code_challenge":"",
  "response_type": "code",
  "user_id":"e76fa28b-b3da-4ef1-bb8a-150151af752e",
  "code_challenge_method": "S256"
}