[package]
name = "oauth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros", "json"] }
hyper = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
bcrypt = "0.15" 
anyhow = "1.0.100"
thiserror = "2.0.17"
sha2 = "0.10.9"
dotenvy = "0.15.7"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7",features = ["runtime-tokio","any","sqlite","postgres","time", "chrono"] }
time = { version = "0.3", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
hex = "0.4"
base64 = "0.22"
rand = "0.8"
urlencoding = "2.1"
